### ISSUE TITLE
Steamworks error 183

### ISSUE THREAD

**Issue by Villads1** [sneak-it/PlayerAnalytics#11]
Hello! I would like to utilize this plugin but am getting these 3 errors upon compiling. I am running on the newest version of Steamworks. Is this plugin simply incompatible & if so, could you refer me to a compatible one, or is something else wrong?

csgo\addons\sourcemod\scripting\include\SteamWorks.inc(273) : error 183: brackets after variable name indicates a fixed-size array, but size is missing or not constant
csgo\addons\sourcemod\scripting\include\SteamWorks.inc(274) : error 183: brackets after variable name indicates a fixed-size array, but size is missing or not constant
csgo\addons\sourcemod\scripting\include\SteamWorks.inc(275) : error 183: brackets after variable name indicates a fixed-size array, but size is missing or not constant

**Comment by sneak-it** [comment]
Not a plugin issue, an include issue. See: https://github.com/KyleSanderson/SteamWorks/pull/37
