### ISSUE TITLE
Russian NickNames 

### ISSUE THREAD

**Issue by arestonelle** [sneak-it/PlayerAnalytics#2]
Hey there!
I'm transfer servers to your forked version (manually change table default charset to utf8mb4) but the russian nicknames are corrupted in db now, they appear like ÐÐµ ÑÐ¼Ð¾Ñ‚Ñ€Ð¸ Ð½Ð° Ð°Ð²Ñƒ
What can i do for fix it? On non-forked version there is no trouble with russian nicks. 

Tnahk you!

**Comment by sneak-it** [comment]
Did this happen in the conversion process, or after, as they are inserted from the server?

**Comment by arestonelle** [comment]
It happens when plugin insert data from server to db.
Currently fixed by editing 64 & 65 lines of .sp
(line 64) SQL_SetCharset(g_DB, "utf8mb4"); to SQL_SetCharset(g_DB, "utf8");
(line 65)  `name varchar(64)` edited by increment varchar to 255.

Dunno why, but utf8mb4 distort Russian charset. With utf8 collation there is no such problem.

**Comment by arestonelle** [comment]
It's a temporary fix. I know that utf8 can support character array only between 0x000 - 0xFFFF, but better have correct names excluding specialised characters instead of nothing at all except English :D

**Comment by sneak-it** [comment]
What version of Sourcemod are you running?

**Comment by arestonelle** [comment]
SourceMod Version Information:
    SourceMod Version: 1.9.0.6280
    SourcePawn Engine: 1.9 MOD P&P V1.3.1, jit-x86 (build 1.9-dev)
    SourcePawn API: v1 = 4, v2 = 12
    Compiled on: May  1 2019 15:46:03
    Built from: https://github.com/alliedmodders/sourcemod/commit/c2d4643
    Build ID: 6280:c2d4643
    http://www.sourcemod.net/

**Comment by sneak-it** [comment]
Can you try this plugin (without any changes) with SM 1.10? The MySQL driver in 1.10 has received a much-needed update, and may make a large difference.

**Comment by arestonelle** [comment]
I think that i can't. It's a live servers with stable sm. I'm afraid to change sm to dev branch at this moment...

**Comment by sneak-it** [comment]
If/when you are able to do so, please let me know if this solves the issue for you. I personally run SM 1.10 on all of my live servers without issue.

**Comment by sneak-it** [comment]
Closing out due to inactivity, feel free to comment back if this is still an issue. SM 1.10 is now the stable branch.
