### ISSUE TITLE
Doubt with plugin features

### ISSUE THREAD

**Issue by paulocrash** [sneak-it/PlayerAnalytics#3]
First of all congratulations for the work and thank you for continuing with it.

I saw that if I continue with the project and apparently it still has all the features of the original plugin.

What I would like to know if he has, or if he plans to add in the future the option to record the time that the player stays in the servidr, time connected of him, without resetting this time.

That is, the total time he has already played on the servers.

**Would this resource already have? That would be the case:**
_**- Duration of play session;**_

Thanks in advance!

**Comment by sneak-it** [comment]
The plugin already records player session time. Every time a player connects, a new row is inserted, and when the player disconnects, their duration is recorded in that row.

**Comment by paulocrash** [comment]
> The plugin already records player session time. Every time a player connects, a new row is inserted, and when the player disconnects, their duration is recorded in that row.
Perfect, another thing, is there any way I can block the view of certain information for players without admin access to the Web Interface they have for it, even for unprivileged players on the servers?

Example, hide for players without any privileges the information of IP, Location of the players.

**Comment by sneak-it** [comment]
What you do for a front-end is your decision, all this plugin does is log all info to a database. How you make that information accessible is outside the scope of the actual plugin.

**Comment by paulocrash** [comment]
Perfect, thanks.
