### ISSUE TITLE
Update GeoIPCity for GeoIP2

### ISSUE THREAD

**Issue by paulocrash** [sneak-it/PlayerAnalytics#4]
I would like to know if you want to upgrade **GeoIPCity** to the new version, **GeoIP2**.

I ask because I currently have the following error when I use the plugin:
```
[20] <FAILED> file" geoipcity.ext.so ": Failed to open: / home / clients / OGP_User_Files / whmcs / 504 / csgo / addons / sourcemod / configs / geoip / GeoIPCity.dat
```
I searched to download `GeoIPCity.dat` but it no longer exists.

Or would you have some correction for this error?

**Comment by sneak-it** [comment]
Maxmind has dropped support of the initial GeoIP and GeoIP versions in favor of GeoIP2. Official GeoIP2 support via Sourcemod is a work in progress: https://github.com/alliedmodders/sourcemod/pull/914

Here is the last known GeoIPCityLite database that I was able to find: https://forums.alliedmods.net/showpost.php?p=2645935&postcount=102

**Comment by paulocrash** [comment]
> Here is the last known GeoIPCityLite database that I was able to find: https://forums.alliedmods.net/showpost.php?p=2645935&postcount=102

Yes, I downloaded this version too, but here comes a file with `nEnrtl` name, while the right one would be a `GeoIPCity.dat` file. I would have some way / setting that I should do with this download file.

[nEnrtl.zip](https://github.com/sneak-it/PlayerAnalytics/files/3407087/nEnrtl.zip)

**Comment by sneak-it** [comment]
Apologies, fixed the zip file: https://share.snksrv.com/f/ypA7GK.zip

**Comment by paulocrash** [comment]
Thank you very much, I will be testing there, anything will return the contact, thanks again!

**Comment by sneak-it** [comment]
@crashzk Went ahead and created a new branch with GeoIP2 support: https://github.com/sneak-it/PlayerAnalytics/tree/geoip2
