### ISSUE TITLE
Support to show Player Analytics only from privileged players

### ISSUE THREAD

**Issue by crashzk** [sneak-it/PlayerAnalytics#9]
I'm using this Web Interface for Player Analytics: https://github.com/Sinclair47/player_analytics

My question would be, can I create a tab / page in this web interface to show the information only of players with privileges?

Would the plugin already support this option? Do I only need to implement it on the web interface?

**Comment by sneak-it** [comment]
By "Players with privileges" you mean players with certain (admin) flags? Absolutely doable, as this plugin records user flags. You would need to modify the web interface to do so - likely a lot of query changes (add `WHERE flags LIKE 'yourflaghere'`).

**Comment by crashzk** [comment]
> By "Players with privileges" you mean players with certain (admin) flags? 

That's right.

> Absolutely doable, as this plugin records user flags. You would need to modify the web interface to do so - likely a lot of query changes (add `WHERE flags LIKE 'yourflaghere'`).

Perfect, thanks, I'll try.
